#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
"${repo_root}/tools/local/lint"
"${repo_root}/tools/local/typecheck"
"${repo_root}/tools/local/test-unit"
